version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./gitea:/data
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "472:472"
    environment:
      - GF_SERVER_ROOT_URL=https://3.110.86.116/grafana
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-Remote-User
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_LOG_MODE=console        # Correct
      - GF_LOG_LEVEL=debug 
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - internal

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    volumes:
      - ./authelia/config:/config 
    ports:
      - "9091:9091"
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gitea
      - authelia
    networks:
      - internal

networks:
  internal:
    driver: bridge
